MVC_Exercises/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Exercises.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC_Exercises.Controllers
{
    public class PeopleController : Controller
    {
        public IActionResult PeopleIndex()
        {
            PeopleViewModel.TempSearchList.Clear();

            if (PeopleViewModel.ListPeople.Count == 0)
            {
                PeopleViewModel.CreatePeopleList();
            }
            PeopleViewModel model = new PeopleViewModel
            {
                TempList = PeopleViewModel.ListPeople
            };

            return View(model);
        }        

        [HttpPost]
        public IActionResult SearchPeopleIndex(string searchSubject, PeopleViewModel model)
        {
            if (searchSubject != null) 
            { 
                PeopleViewModel.SearchPeopleList(searchSubject);
                model.TempList = PeopleViewModel.TempSearchList;
            }
            else
            {
                PeopleViewModel.Message = "";
                PeopleViewModel.Message2 = "";

                PeopleViewModel.TempSearchList.Clear();
                model.TempList = PeopleViewModel.ListPeople;
            }

            return View("PeopleIndex", model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PeopleViewModel model)
        {
            model.Id = PeopleViewModel.NewId;
            PeopleViewModel.ListPeople.Add(model);
            PeopleViewModel.NewId++;

            return RedirectToAction("PeopleIndex");
        }

        public IActionResult Delete(int Id)
        {
            if (Id != 0) 
            {
                var people = PeopleViewModel.ListPeople.Find(x => x.Id == Id);
                PeopleViewModel.ListPeople.Remove(people);
            }
            else
            {
                PeopleViewModel.Message = "Something went wrong. No Id found.";
            }

            return RedirectToAction("PeopleIndex");
        }

        public IActionResult SortAlpha(PeopleViewModel model, string _sortCriteria, string _landingPage)
        {
            string LandingPage = _landingPage;
            if (_sortCriteria == "Name")
            {
                PeopleViewModel.OrderOrderName = !PeopleViewModel.OrderOrderName;
                PeopleViewModel.SortListName();

                //Copy Sort result to TempList to show on page
                model.TempList = PeopleViewModel.TempSearchList;
            }

            if (_sortCriteria == "City")
            {
                PeopleViewModel.OrderOrderCity = !PeopleViewModel.OrderOrderCity;
                PeopleViewModel.SortListCity();

               model.TempList = PeopleViewModel.TempSearchList;
            }

            return View(LandingPage, model);
        }

        public IActionResult PeoplePartial()
        {
            PeopleViewModel.TempSearchList.Clear();

            if (PeopleViewModel.ListPeople.Count == 0)
            {
                PeopleViewModel.CreatePeopleList();
            }
            PeopleViewModel model = new PeopleViewModel
            {
                TempList = PeopleViewModel.ListPeople
            };

            return View(model);
        }
    }
}

MVC_Exercises/Views/Shared/PeoplePartialView.cshtml
@model PeopleViewModel


            <td>
                @Html.DisplayFor(modelItem => Model.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.City)
            </td>
            <td>@Html.ActionLink("Delete", "Delete", new { Id = Model.Id })</td>

        

MVC_Exercises/Views/Shared/View.cshtml
@model PeopleViewModel

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.TempList) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

MVC_Exercises/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container bg-color">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Exercises</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">CV |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Projects">My Lexicon Projects |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="FeverCheck">FeverCheck 2000 |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GuessingGame">GuessingGame 2000 |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="PeopleIndex">PeoplesList 2000 |</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="PeoplePartial">ListInPartialView 2000</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Date.ToShortDateString() - MVC_Exercises -  Nicolas Lewentorp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>